import React, { useEffect, useRef, useState, Suspense, lazy } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUp, ArrowUpRight, AudioLines, Mic, MessageSquare, Plus, Sparkles, Search, Code2, Brain, X, ShieldCheck, Volume2, VolumeX, Trash2 } from 'lucide-react';
import './style.css';
const Orb=lazy(()=>import('./Orb'));
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const suggestions=[{icon:Sparkles,title:'Make something click',sub:'Break down a complex idea',prompt:'Explain how neural networks learn, with a simple analogy.'},{icon:Code2,title:'Build your next idea',sub:'Create a Python starting point',prompt:'Create a Python file for a command-line to-do list.'},{icon:Brain,title:'Keep a thought close',sub:'Save a note for later',prompt:'Take a note to explore my next big idea this weekend.'},{icon:Search,title:'Follow your curiosity',sub:'Find something worth exploring',prompt:'Search YouTube for creative coding with Three.js'}];
function App(){
 const [token,setToken]=useState(()=>localStorage.getItem('nova-token')||'');const [login,setLogin]=useState(false);const [code,setCode]=useState('');const [loginBusy,setLoginBusy]=useState(false);
 const [input,setInput]=useState('');const [messages,setMessages]=useState([]);const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);const [speaking,setSpeaking]=useState(false);const [voice,setVoice]=useState(false);const [error,setError]=useState('');const [online,setOnline]=useState(false);const [panel,setPanel]=useState(false);
 const recognition=useRef(null), bottom=useRef(null);
 useEffect(()=>{fetch(API+'/healthz',{signal:AbortSignal.timeout(10000)}).then(r=>setOnline(r.ok)).catch(()=>setOnline(false));return ()=>{recognition.current?.abort();window.speechSynthesis?.cancel();}},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[messages,busy]);
 async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},signal:AbortSignal.timeout(75000)});const data=await r.json();if(!r.ok){if(r.status===401){setToken('');localStorage.removeItem('nova-token');setLogin(true)}throw Error(typeof data.detail==='string'?data.detail:'Please check your request and try again.')}return data}
 async function connect(e){e.preventDefault();setLoginBusy(true);setError('');try{const data=await request('/api/session',{method:'POST',body:JSON.stringify({access_code:code})});localStorage.setItem('nova-token',data.token);setToken(data.token);setCode('');setLogin(false);setOnline(true)}catch(e){setError(e.message)}finally{setLoginBusy(false)}}
 async function send(text=input){if(!text.trim()||busy||listening)return;if(!token){setInput(text);setLogin(true);return}window.speechSynthesis?.cancel();setSpeaking(false);setInput('');setError('');setMessages(m=>[...m,{role:'user',text}]);setBusy(true);try{const data=await request('/api/chat',{method:'POST',body:JSON.stringify({text,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setMessages(m=>[...m,{role:'assistant',...data}]);setOnline(true);if(voice&&window.speechSynthesis){const speech=new SpeechSynthesisUtterance(data.text.slice(0,700));speech.onstart=()=>setSpeaking(true);speech.onend=speech.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(speech)}}catch(e){setError(e.name==='TimeoutError'?'Nova took too long to respond. Please try again.':e.message)}finally{setBusy(false)}}
 function mic(){if(listening){recognition.current?.stop();return}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!window.isSecureContext){setError('Microphone access requires HTTPS or localhost.');return}if(!Speech){setError('Voice recognition is unavailable in this browser. You can type your message instead.');return}if(!token){setLogin(true);return}window.speechSynthesis?.cancel();setSpeaking(false);setError('');const r=new Speech();recognition.current=r;r.lang='en-US';r.interimResults=true;r.onresult=e=>setInput(Array.from(e.results).map(x=>x[0].transcript).join(' '));r.onerror=e=>{setError(e.error==='not-allowed'?'Microphone permission was denied. Allow it in your browser settings.':'Voice input stopped: '+e.error);setListening(false)};r.onend=()=>setListening(false);try{r.start();setListening(true)}catch{setListening(false);setError('Could not start the microphone. Please try again.')}}
 function download(action){const url=URL.createObjectURL(new Blob([action.content],{type:'text/x-python'}));const a=document.createElement('a');a.href=url;a.download='nova_generated.py';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function erase(){if(!window.confirm('Delete all notes, memories, and model conversation stored for this browser session?'))return;try{await request('/api/data',{method:'DELETE'});setMessages([]);setPanel(false)}catch(e){setError(e.message)}}
 return <div className="shell"><aside className="rail"><a className="brand" href="#" aria-label="Nova home"><AudioLines size={25}/></a><button className="rail-btn selected" title="Assistant" aria-label="Assistant" onClick={()=>setPanel(false)}><MessageSquare size={20}/></button><button className="rail-btn" title="New view" aria-label="Clear visible conversation" disabled={busy||listening} onClick={()=>{setMessages([]);setError('')}}><Plus size={22}/></button><div className="rail-bottom"><button className="avatar" title="Privacy and session" aria-label="Privacy and session" onClick={()=>setPanel(!panel)}>N</button></div></aside>
 <main><header><a href="#" className="wordmark">nova<span> / </span><small>PERSONAL INTELLIGENCE</small></a><div className="header-right"><span className="connection"><i className={online?'on':''}/>{online?'API online':'API offline'}</span><button className="connect" onClick={()=>token?setPanel(!panel):setLogin(true)}>{token?'Your workspace':'Connect'}<ArrowUpRight size={14}/></button></div></header>
 <div className="workspace"><section className={'hero '+(messages.length?'compact':'')}><div className="eyebrow"><span/> A LITTLE SPACE FOR BIG IDEAS</div><h1>Your ideas,<br/><em>amplified.</em></h1><p>Think out loud. Find a new direction.<br/>Make everyday things a little more extraordinary.</p><div className="orb-wrap"><div className="orb-glow"/><Suspense fallback={<div className="fallback-orb"/>}><Orb active={listening||speaking||busy}/></Suspense><div className="orb-caption"><span className={busy||listening?'pulse':''}/>{listening?'Listening to you':busy?'Connecting the dots':speaking?'Speaking':'Ready when you are'}</div></div></section>
 {messages.length===0?<section className="starters"><div className="section-label">WHERE SHALL WE START?<span>Pick a thought. Or bring your own.</span></div><div className="cards">{suggestions.map(({icon:Icon,title,sub,prompt})=><button key={title} className="card" onClick={()=>send(prompt)} disabled={busy}><Icon size={21}/><ArrowUpRight size={15} className="card-arrow"/><strong>{title}</strong><span>{sub}</span></button>)}</div></section>:<section className="conversation" aria-label="Conversation" aria-live="polite">{messages.map((m,i)=><article key={i} className={'message '+m.role}><div className="speaker">{m.role==='assistant'?<AudioLines size={16}/>:<span>Y</span>}{m.role==='assistant'?'NOVA':'YOU'}</div><p>{m.text}</p>{m.action?.type==='link'&&/^https:\/\//.test(m.action.url)&&<a className="action" href={m.action.url} target="_blank" rel="noopener noreferrer">{m.action.label}<ArrowUpRight size={14}/></a>}{m.action?.type==='download'&&<button className="action" onClick={()=>download(m.action)}>Download Python file<Code2 size={14}/></button>}</article>)}{busy&&<div className="thinking">Nova is thinking<span>•••</span></div>}<div ref={bottom}/></section>}
 <section className="composer-wrap">{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><AudioLines className="input-icon" size={23}/><input aria-label="Message Nova" value={input} maxLength={4000} onChange={e=>setInput(e.target.value)} placeholder={listening?'Listening… review your words, then send.':'Ask anything, or just start talking…'} disabled={busy}/><button type="button" className={listening?'mic live':'mic'} aria-label={listening?'Stop microphone':'Start microphone'} onClick={mic} disabled={busy}><Mic size={19}/></button><button className="send" aria-label="Send message" disabled={busy||listening||!input.trim()}><ArrowUp size={20}/></button></form><div className="composer-footer"><span><ShieldCheck size={13}/> Your keys stay on the server</span><button onClick={()=>{setVoice(!voice);window.speechSynthesis?.cancel();setSpeaking(false)}}>{voice?<Volume2 size={14}/>:<VolumeX size={14}/>}Voice replies {voice?'on':'off'}</button></div><p className="voice-note">Voice recognition may use your browser’s speech service. Review the transcript before sending.</p></section></div><footer><span>NOVA / YOUR PERSONAL AI WORKSPACE</span><span>Built for the way you think.</span></footer></main>
 {panel&&<div className="shade" onClick={()=>setPanel(false)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close" onClick={()=>setPanel(false)}><X/></button><ShieldCheck className="mint"/><h2>Your workspace.</h2><p>Notes, memories, and AI chat are stored on the server, separately for this browser session. Each collection keeps up to 100 entries. Your session lasts 30 days.</p><p>“New view” clears only the visible chat. Delete your saved data before disconnecting if you want it removed. The service owner can access server storage.</p><button className="wide" disabled={!token||busy} onClick={erase}><Trash2 size={16}/> Delete my saved data</button><button className="wide secondary" disabled={busy||listening} onClick={()=>{localStorage.removeItem('nova-token');setToken('');setMessages([]);setPanel(false)}}>Disconnect this browser</button></section></div>}
 {login&&<div className="shade"><form className="modal" onSubmit={connect}><button type="button" className="close" aria-label="Close" onClick={()=>setLogin(false)}><X/></button><AudioLines className="mint" size={30}/><h2>A space of your own.</h2><p>Enter the access code shared by the workspace owner. Your notes and conversations stay separate from other visitors.</p><label htmlFor="access">Workspace access code</label><input id="access" autoFocus type="password" autoComplete="current-password" value={code} onChange={e=>setCode(e.target.value)} required maxLength={256}/>{error&&<p role="alert" className="login-error">{error}</p>}<button className="wide" disabled={loginBusy}>{loginBusy?'Connecting…':'Enter workspace'}<ArrowUpRight size={17}/></button></form></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
